<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.5</version>
        <relativePath/> 
    </parent>

    <artifactId>services</artifactId>
    <packaging>pom</packaging>

    <name>Business Services</name>
    <description> Aggregator for cloud infrastructure modules (Eureka ,Config , Gateway)</description>

    <modules>
        <module>booking-service</module>
        <module>category-service</module>
        <module>eureka-server</module>
        <module>gateway-server</module>
        <module>notifications</module>
        <module>payment-service</module>
        <module>review</module>
        <module>salon-service</module>
        <module>service-offering</module>
        <module>user-service</module>
        <module>docker-compose</module>
        

    </modules>

    

    <dependencies>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>


</project>