server:
  port: 5010

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://bookingdb:3306/bookingdb_yt
    username: root
    password: Nha1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: eurakserver

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://eurakserver:8070/eureka/"

      