spring.application.name=payment-service

server.port=5011


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/paymentdb_yt?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=Nha1234567


bakong.api.key="your bakong api key"
bakong.api.secret="your bakong api secret"

stripe.api.key="your stripe api key"

razorpay.api.key="your bakong api key"
razorpay.api.secret="your bakong api secret"