server:
  port: 5012

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb_yt?createDatabaseIfNotExist=true
    username: root
    password: Nha1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


stripe:
  api:
    key: your_stripe_api_key

bakong:
  khqr:
    account-id: sopanha_phin@bkrt
    account-number: 85599646350
    bank-name: VATTANAC BANK
  
  api:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiYzNlZDU3ODA0ZTQzNGJjMyJ9LCJpYXQiOjE3Nzc4MTg0MTAsImV4cCI6MTc4NTU5NDQxMH0.gJ_1Xu54w3Q3De0ZinVJPZ0AMKkXrgumy1pmKLU5cP4
    base-url: https://api-bakong.nbc.gov.kh

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
    