export const INITIATE_BAKONG_PAYMENT_REQUEST = "INITIATE_BAKONG_PAYMENT_REQUEST";
export const INITIATE_BAKONG_PAYMENT_SUCCESS = "INITIATE_BAKONG_PAYMENT_SUCCESS";
export const INITIATE_BAKONG_PAYMENT_FAILURE = "INITIATE_BAKONG_PAYMENT_FAILURE";

export const INITIATE_STRIPE_PAYMENT_REQUEST = "INITIATE_STRIPE_PAYMENT_REQUEST";
export const INITIATE_STRIPE_PAYMENT_SUCCESS = "INITIATE_STRIPE_PAYMENT_SUCCESS";
export const INITIATE_STRIPE_PAYMENT_FAILURE = "INITIATE_STRIPE_PAYMENT_FAILURE";