export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILURE = "CREATE_BOOKING_FAILURE";

export const FETCH_CUSTOMER_BOOKINGS_REQUEST = "FETCH_CUSTOMER_BOOKINGS_REQUEST";
export const FETCH_CUSTOMER_BOOKINGS_SUCCESS = "FETCH_CUSTOMER_BOOKINGS_SUCCESS";
export const FETCH_CUSTOMER_BOOKINGS_FAILURE = "FETCH_CUSTOMER_BOOKINGS_FAILURE";

export const FETCH_SALON_BOOKINGS_REQUEST = "FETCH_SALON_BOOKINGS_REQUEST";
export const FETCH_SALON_BOOKINGS_SUCCESS = "FETCH_SALON_BOOKINGS_SUCCESS";
export const FETCH_SALON_BOOKINGS_FAILURE = "FETCH_SALON_BOOKINGS_FAILURE";

export const UPDATE_BOOKING_STATUS_REQUEST = "UPDATE_BOOKING_STATUS_REQUEST";
export const UPDATE_BOOKING_STATUS_SUCCESS = "UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_FAILURE = "UPDATE_BOOKING_STATUS_FAILURE";


export const GET_ALL_SALON_REQUEST = "GET_ALL_SALON_REQUEST";
export const GET_ALL_SALON_SUCCESS = "GET_ALL_SALON_SUCCESS";
export const GET_ALL_SALON_FAILURE = "GET_ALL_SALON_FAILURE";

export const FETCH_BOOKED_SERVICES_REQUEST = "FETCH_BOOKED_SERVICES_REQUEST";
export const FETCH_BOOKED_SERVICES_SUCCESS = "FETCH_BOOKED_SERVICES_SUCCESS";
export const FETCH_BOOKED_SERVICES_FAILURE = "FETCH_BOOKED_SERVICES_FAILURE";

